name: Deploy application on production & sandbox servers with restricted SSH access
on:
    push:
        branches:
            - main

permissions:
  contents: read

jobs:
    deployment:
        name: Deployment on production & sandbox servers with restricted access
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: SSH to production server and trigger deploy for branch main
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY_RESTRICTED }}
                  port: ${{ secrets.SSH_PORT }}
                  script: main
            - name: SSH to sandbox server and trigger deploy for branch main
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SANDBOX_SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY_RESTRICTED }}
                  port: ${{ secrets.SSH_PORT }}
                  script: main
